chore(cli): install modules before bootstrap in integ tests (#10297)
Integ tests are failing with:

```console
Error: Cannot find module '@aws-cdk/core'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/tmp/cdk-integ-0gjmfcdff6x/app.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Subprocess exited with error 1
❌ Error: 'cdk bootstrap aws://1234567890/us-west-2' exited with error code 1
```

This is because we try to bootstrap before installing the necessary modules. Since our app has a `cdk.json` file and we are running inside that directory, `cdk bootstrap` tries to synth the app to detect environments, and fails.

Just install all the modules before bootstrap.

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*